### ISSUE TITLE
Mac OSX x64 binaries are skipped

### ISSUE THREAD

**Issue by fcollonval** [conda-forge/coolprop-feedstock#27]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The binaries for Mac OSX x64 are skipped since https://github.com/conda-forge/coolprop-feedstock/pull/26 because actually the assets are overridden by those downloaded from PyPI.org:

```
...
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/tests/test_plots.py to test_plots.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/tests/test_Props.py to test_Props.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/tests/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/tests/test_CoolPropState.py to test_CoolPropState.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/BibtexParser.py to BibtexParser.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/HumidAirProp.py to HumidAirProp.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/GUI/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/GUI/CoolPropGUI.py to CoolPropGUI.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/GUI/PsychScript.py to PsychScript.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/State.py to State.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/ConsistencyPlots_pcsaft.py to ConsistencyPlots_pcsaft.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/PsychChart.py to PsychChart.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/SimpleCycles.py to SimpleCycles.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/psy.py to psy.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/Plots.py to Plots.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/Common.py to Common.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/SimpleCyclesCompression.py to SimpleCyclesCompression.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/ConsistencyPlots.py to ConsistencyPlots.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/PsychScript.py to PsychScript.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/Tests.py to Tests.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/Plots/SimpleCyclesExpansion.py to SimpleCyclesExpansion.cpython-310.pyc
creating stub loader for CoolProp/CoolProp.cpython-310-darwin.so
creating stub loader for CoolProp/_constants.cpython-310-darwin.so
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/CoolProp.py to CoolProp.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/CoolProp/_constants.py to _constants.cpython-310.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying CoolProp.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying CoolProp.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying CoolProp.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying CoolProp.egg-info/not-zip-safe -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying CoolProp.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg
creating $PREFIX/lib/python3.10/site-packages/CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg
Extracting CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg to $PREFIX/lib/python3.10/site-packages
Adding CoolProp 6.4.1 to easy-install.pth file

Installed $PREFIX/lib/python3.10/site-packages/CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg
Processing dependencies for CoolProp==6.4.1
Searching for CoolProp==6.4.1
Reading https://pypi.org/simple/CoolProp/
/Users/runner/miniforge3/conda-bld/coolprop_1670248017981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/56/04/b200dc07644456f7a8cec3926bee652bdf1ef4cd9e317bdb0a3d50fc3466/CoolProp-6.4.1-cp310-cp310-macosx_10_9_x86_64.whl#sha256=2a2a4af5d5981cecaea719d991d9c469cc33f3e81d908072060c315596c61f2d
Best match: CoolProp 6.4.1
Processing CoolProp-6.4.1-cp310-cp310-macosx_10_9_x86_64.whl
removing '$PREFIX/lib/python3.10/site-packages/CoolProp-6.4.1-py3.10-macosx-10.9-x86_64.egg' (and everything under it)
Installing CoolProp-6.4.1-cp310-cp310-macosx_10_9_x86_64.whl to $PREFIX/lib/python3.10/site-packages
CoolProp 6.4.1 is already the active version in easy-install.pth
...
```

### Installed packages

```shell
_
```

### Environment info

```shell
_
```

**Comment by danilomendesdias** [comment]
I think this was solved by https://github.com/conda-forge/coolprop-feedstock/pull/35, so I'm closing this one.
Let me know if I understood this incorrectly.

**Comment by danilomendesdias** [comment]
Ah, something similar is happening again in Python 3.13:
````
2024-09-15T03:59:38.1673280Z   """Thermal efficiency
2024-09-15T03:59:38.1676710Z Adding CoolProp 6.6.0 to easy-install.pth file
2024-09-15T03:59:38.1699850Z 
2024-09-15T03:59:38.1704490Z Installed $PREFIX/lib/python3.13/site-packages/CoolProp-6.6.0-py3.13-macosx-10.13-x86_64.egg
2024-09-15T03:59:38.1727340Z Processing dependencies for CoolProp==6.6.0
2024-09-15T03:59:38.1739940Z Searching for CoolProp==6.6.0
2024-09-15T03:59:38.1764110Z Reading https://pypi.org/simple/CoolProp/
2024-09-15T03:59:38.1774860Z Downloading https://files.pythonhosted.org/packages/13/88/35c88960cf20cf483f1e2127ad999fce4528451ad37173064cdcb3834ebf/CoolProp-6.6.0.tar.gz#sha256=cf6fad704b3ae00f4df309cfd1e2ee48d155886b569a73f2cc38a57eda463082
2024-09-15T03:59:39.5328640Z Best match: CoolProp 6.6.0
2024-09-15T03:59:39.5330030Z Processing CoolProp-6.6.0.tar.gz
2024-09-15T03:59:42.0234530Z Writing /tmp/easy_install-247s6x0d/CoolProp-6.6.0/setup.cfg
2024-09-15T03:59:42.0235620Z Running CoolProp-6.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-247s6x0d/CoolProp-6.6.0/egg-dist-tmp-my93ioco
2024-09-15T03:59:42.0698800Z /tmp/easy_install-247s6x0d/CoolProp-6.6.0/setup.py:60: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
2024-09-15T03:59:42.0699930Z   osx_target = LooseVersion(get_config_var('MACOSX_DEPLOYMENT_TARGET'))
2024-09-15T03:59:42.0700890Z /tmp/easy_install-247s6x0d/CoolProp-6.6.0/setup.py:61: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
2024-09-15T03:59:42.0701720Z   osx_compiler = LooseVersion('0.0')
2024-09-15T03:59:42.0702310Z /tmp/easy_install-247s6x0d/CoolProp-6.6.0/setup.py:62: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
2024-09-15T03:59:42.0704550Z   osx_version = LooseVersion('0.0')
2024-09-15T03:59:42.1300000Z /tmp/easy_install-247s6x0d/CoolProp-6.6.0/setup.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
2024-09-15T03:59:42.2219950Z   osx_compiler = LooseVersion(line)
2024-09-15T03:59:42.2224320Z OSX build detected, targetting 10.13 using clang/gcc v14.0.0.
2024-09-15T03:59:42.2226250Z Cython will not be used; cy_ext is cpp
2024-09-15T03:59:42.2229240Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.13/site-packages/setuptools/__init__.py:88: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
2024-09-15T03:59:42.2232480Z !!
2024-09-15T03:59:42.2235170Z 
2024-09-15T03:59:42.2237150Z         ********************************************************************************
2024-09-15T03:59:42.2239170Z         Requirements should be satisfied by a PEP 517 installer.
2024-09-15T03:59:42.2241280Z         If you are using pip, you can try `pip install --use-pep517`.
2024-09-15T03:59:42.2243330Z         ********************************************************************************
2024-09-15T03:59:42.2245090Z 
2024-09-15T03:59:42.2246930Z !!
2024-09-15T03:59:42.2248830Z   dist.fetch_build_eggs(dist.setup_requires)
2024-09-15T03:59:42.5796290Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
2024-09-15T03:59:42.5797570Z !!
2024-09-15T03:59:42.5797680Z 
2024-09-15T03:59:42.5798000Z         ********************************************************************************
2024-09-15T03:59:42.5798500Z         Please avoid running ``setup.py`` directly.
2024-09-15T03:59:42.5798850Z         Instead, use pypa/build, pypa/installer or other
2024-09-15T03:59:42.5799210Z         standards-based tools.
2024-09-15T03:59:42.5799430Z 
2024-09-15T03:59:42.5799890Z         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
2024-09-15T03:59:42.5800430Z         ********************************************************************************
2024-09-15T03:59:42.5800660Z 
2024-09-15T03:59:42.5800980Z !!
2024-09-15T03:59:42.5801250Z   self.initialize_options()
2024-09-15T03:59:44.7423750Z CoolProp/CoolProp.cpp:1303:59: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
2024-09-15T03:59:44.7424970Z  1303 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)
2024-09-15T03:59:44.7425340Z       |                                                           ^
2024-09-15T03:59:44.7428110Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
2024-09-15T03:59:44.7429700Z    10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
2024-09-15T03:59:44.7430170Z       | ^
2024-09-15T03:59:44.7431410Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
2024-09-15T03:59:44.7432730Z   251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
2024-09-15T03:59:44.7433060Z       |                                                      ^
2024-09-15T03:59:44.7434320Z CoolProp/CoolProp.cpp:1305:11: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
2024-09-15T03:59:44.7434890Z  1305 |     const Py_UNICODE *u_end = u;
2024-09-15T03:59:44.7435430Z       |           ^
2024-09-15T03:59:44.7437600Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
2024-09-15T03:59:44.7439280Z    10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
2024-09-15T03:59:44.7440180Z       | ^
2024-09-15T03:59:44.7441500Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
2024-09-15T03:59:44.7442930Z   251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
2024-09-15T03:59:44.7443430Z       |                                                      ^
2024-09-15T04:00:10.7250020Z 2 warnings generated.
2024-09-15T04:04:33.0773490Z src/Helmholtz.cpp:1241:9: warning: 'all' has a non-throwing exception specification but can still throw [-Wexceptions]
2024-09-15T04:04:33.0774510Z  1241 |         throw ValueError("T_red needs to be stored somewhere for GERG2004Sinh");
2024-09-15T04:04:33.0774850Z       |         ^
2024-09-15T04:04:33.0775250Z src/Helmholtz.cpp:1230:34: note: function declared non-throwing here
2024-09-15T04:04:33.0776010Z  1230 | void IdealHelmholtzGERG2004Sinh::all(const CoolPropDbl& tau, const CoolPropDbl& delta, HelmholtzDerivatives& derivs) throw() {
2024-09-15T04:04:33.0782230Z       |                                  ^                                                                                   ~~~~~~~
2024-09-15T04:04:33.0783760Z src/Helmholtz.cpp:1272:9: warning: 'all' has a non-throwing exception specification but can still throw [-Wexceptions]
2024-09-15T04:04:33.0784530Z  1272 |         throw ValueError("T_red needs to be stored somewhere for GERG2004Cosh");
2024-09-15T04:04:33.0784980Z       |         ^
2024-09-15T04:04:33.0785510Z src/Helmholtz.cpp:1261:34: note: function declared non-throwing here
2024-09-15T04:04:33.0786250Z  1261 | void IdealHelmholtzGERG2004Cosh::all(const CoolPropDbl& tau, const CoolPropDbl& delta, HelmholtzDerivatives& derivs) throw() {
2024-09-15T04:04:33.0786810Z       |                                  ^                                                                                   ~~~~~~~
2024-09-15T04:04:34.6284880Z 2 warnings generated.
2024-09-15T04:05:21.9643510Z CoolProp/_constants.cpp:1288:59: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
2024-09-15T04:05:21.9645310Z  1288 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)
2024-09-15T04:05:21.9645810Z       |                                                           ^
2024-09-15T04:05:21.9646930Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
2024-09-15T04:05:21.9651040Z    10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
2024-09-15T04:05:21.9652070Z       | ^
2024-09-15T04:05:21.9653520Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
2024-09-15T04:05:21.9654470Z   251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
2024-09-15T04:05:21.9654930Z       |                                                      ^
2024-09-15T04:05:21.9655410Z CoolProp/_constants.cpp:1290:11: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
2024-09-15T04:05:21.9655910Z  1290 |     const Py_UNICODE *u_end = u;
2024-09-15T04:05:21.9656300Z       |           ^
2024-09-15T04:05:21.9657360Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
2024-09-15T04:05:21.9658270Z    10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
2024-09-15T04:05:21.9658690Z       | ^
2024-09-15T04:05:21.9659590Z /Users/runner/miniforge3/conda-bld/coolprop_1726372376230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
2024-09-15T04:05:21.9660470Z   251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
2024-09-15T04:05:21.9661050Z       |                                                      ^
2024-09-15T04:05:23.8481460Z 2 warnings generated.
2024-09-15T04:05:24.0089870Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/PsychChart.py:53: SyntaxWarning: invalid escape sequence '\c'
2024-09-15T04:05:24.0090670Z   return indented_segment("""
2024-09-15T04:05:24.0091220Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/PsychChart.py:93: SyntaxWarning: invalid escape sequence '\p'
2024-09-15T04:05:24.0091740Z   return indented_segment("""
2024-09-15T04:05:24.0360200Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/SimpleCyclesCompression.py:23: SyntaxWarning: invalid escape sequence '\e'
2024-09-15T04:05:24.0361200Z   """Carnot efficiency
2024-09-15T04:05:24.0361990Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/SimpleCyclesCompression.py:35: SyntaxWarning: invalid escape sequence '\e'
2024-09-15T04:05:24.0362640Z   """Carnot efficiency
2024-09-15T04:05:24.0444640Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/SimpleCyclesExpansion.py:23: SyntaxWarning: invalid escape sequence '\e'
2024-09-15T04:05:24.0445320Z   """Carnot efficiency
2024-09-15T04:05:24.0445860Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/SimpleCyclesExpansion.py:35: SyntaxWarning: invalid escape sequence '\e'
2024-09-15T04:05:24.0446380Z   """Thermal efficiency
2024-09-15T04:05:24.0447950Z build/bdist.macosx-10.13-x86_64/egg/CoolProp/Plots/SimpleCyclesExpansion.py:166: SyntaxWarning: invalid escape sequence '\e'
2024-09-15T04:05:24.0448690Z   """Thermal efficiency
2024-09-15T04:05:24.3056340Z No eggs found in /tmp/easy_install-247s6x0d/CoolProp-6.6.0/egg-dist-tmp-my93ioco (setup script problem?)
2024-09-15T04:05:24.7320640Z files removed.
2024-09-15T04:05:24.7329640Z error: The 'CoolProp==6.6.0' distribution was not found and is required by the application
2024-09-15T04:05:26.2178930Z Traceback (most recent call last):
2024-09-15T04:05:26.2180460Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 2558, in build
2024-09-15T04:05:26.2200300Z     utils.check_call_env(
2024-09-15T04:05:26.2201280Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/utils.py", line 404, in check_call_env
2024-09-15T04:05:26.2207130Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-09-15T04:05:26.2207720Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-15T04:05:26.2208940Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
2024-09-15T04:05:26.2210170Z     raise subprocess.CalledProcessError(proc.returncode, _args)
2024-09-15T04:05:26.2211680Z subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/coolprop_1726372376230/work/conda_build.sh']' returned non-zero exit status 1.
2024-09-15T04:05:26.2212220Z 
2024-09-15T04:05:26.2212780Z The above exception was the direct cause of the following exception:
2024-09-15T04:05:26.2213380Z 
2024-09-15T04:05:26.2214300Z Traceback (most recent call last):
2024-09-15T04:05:26.2214970Z   File "/Users/runner/miniforge3/bin/conda-build", line 11, in <module>
2024-09-15T04:05:26.2215440Z     sys.exit(execute())
2024-09-15T04:05:26.2215700Z              ^^^^^^^^^
2024-09-15T04:05:26.2216280Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 589, in execute
2024-09-15T04:05:26.2225590Z     api.build(
2024-09-15T04:05:26.2227220Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/api.py", line 209, in build
2024-09-15T04:05:26.2230730Z     return build_tree(
2024-09-15T04:05:26.2232520Z            ^^^^^^^^^^^
2024-09-15T04:05:26.2234230Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 3712, in build_tree
2024-09-15T04:05:26.2239770Z     packages_from_this = build(
2024-09-15T04:05:26.2241470Z                          ^^^^^^
2024-09-15T04:05:26.2243210Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 2566, in build
2024-09-15T04:05:26.2246820Z     raise BuildScriptException(str(exc), caused_by=exc) from exc
2024-09-15T04:05:26.2249230Z conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/coolprop_1726372376230/work/conda_build.sh']' returned non-zero exit status 1.
2024-09-15T04:05:33.6912300Z 
2024-09-15T04:05:33.6982370Z ##[error]Bash exited with code '1'.
2024-09-15T04:05:33.7030010Z ##[section]Finishing: Run OSX build

**Comment by fcollonval** [comment]
For what I saw, it is still there in #35

The [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1028276&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00) for osx osx_64_python3.10.____cpython Run OSX build states:

```
...
creating dist
creating $PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg
Extracting CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg to $PREFIX/lib/python3.10/site-packages
Adding CoolProp 6.6.0 to easy-install.pth file

Installed $PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg
Processing dependencies for CoolProp==6.6.0
Searching for CoolProp==6.6.0
Reading https://pypi.org/simple/CoolProp/
Downloading https://files.pythonhosted.org/packages/f8/32/2aa4309b9d47fd7ba7b06fb8a5f2b4414acfbf3e103c57256ea3e8f5d559/CoolProp-6.6.0-cp310-cp310-macosx_10_9_x86_64.whl#sha256=e628b334548f5eaf7d7508b673d3a1bcf61c8691c0d020057eb0c9f842e8b702
Best match: CoolProp 6.6.0
Processing CoolProp-6.6.0-cp310-cp310-macosx_10_9_x86_64.whl
removing '$PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg' (and everything under it)
Installing CoolProp-6.6.0-cp310-cp310-macosx_10_9_x86_64.whl to $PREFIX/lib/python3.10/site-packages
CoolProp 6.6.0 is already the active version in easy-install.pth
detected new path './CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg'

Installed $PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-macosx-10.9-x86_64.egg
Finished processing dependencies for CoolProp==6.6.0
files removed.
...
```

If you compare for Linux 3.10, you have the following logs:

```
...
creating dist
creating 'dist/CoolProp-6.6.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CoolProp-6.6.0-py3.10-linux-x86_64.egg
creating $PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-linux-x86_64.egg
Extracting CoolProp-6.6.0-py3.10-linux-x86_64.egg to $PREFIX/lib/python3.10/site-packages
Adding CoolProp 6.6.0 to easy-install.pth file

Installed $PREFIX/lib/python3.10/site-packages/CoolProp-6.6.0-py3.10-linux-x86_64.egg
Processing dependencies for CoolProp==6.6.0
Finished processing dependencies for CoolProp==6.6.0
files removed.
...
```

I have no clue why it consider the .egg install as invalid for MacOS when it is ok in Linux and Windows (BTW)

<details>
<summary>Windows log</summary>
<code>
creating dist
creating 'dist\CoolProp-6.6.0-py3.10-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing CoolProp-6.6.0-py3.10-win-amd64.egg
creating d:\bld\coolprop_1726362729509\_h_env\lib\site-packages\CoolProp-6.6.0-py3.10-win-amd64.egg
Extracting CoolProp-6.6.0-py3.10-win-amd64.egg to d:\bld\coolprop_1726362729509\_h_env\lib\site-packages
Adding CoolProp 6.6.0 to easy-install.pth file

Installed d:\bld\coolprop_1726362729509\_h_env\lib\site-packages\coolprop-6.6.0-py3.10-win-amd64.egg
Processing dependencies for CoolProp==6.6.0
Finished processing dependencies for CoolProp==6.6.0
files removed.
</code>
</details>

**Comment by fcollonval** [comment]
cc @conda-forge/help-python if anyone saw something similar elsewhere

**Comment by danilomendesdias** [comment]
Finally closed by https://github.com/conda-forge/coolprop-feedstock/pull/37
